### ISSUE TITLE
Semana 1: Fundamentos del Lenguaje C#

### ISSUE THREAD

**Issue by FormacionFCT** [FormacionFCT/Practicas-Andres#6]
Estudiar : 

- Variables, tipos de datos, operadores, estructuras de control (if, switch, for, while).
- Clases y objetos en C#.

Curso de píldoras informáticas - C# : https://www.youtube.com/watch?v=K4JUqONrb8E&list=PLU8oAlHdN5BmpIQGDSHo5e1r4ZYWQ8m4B&index=1

**Comment by juanmasolsan** [comment]
@FormacionFCT Esto es una prueba.
